module.exports = [
{
    chargeSocialesSarlSasTitle : "Charges sociales en SAS vs. SARL : quelles différences ?",
    explanation :"Les charges sociales correspondent aux taxes et aux cotisations calculées sur le salaire brut des salariés et des employeurs. Elles permettent de couvrir leur protection sociale (notamment la retraite, la maladie, les allocations familiales et la formation professionnelle). Ces cotisations sont prélevées sur les salaires ou les dividendes du gérant d’une Société à responsabilité limitée (SARL) et du président d’une Société par actions simplifiée (SAS). Le taux de ces charges et le niveau de protection sociale varient en fonction du statut social du dirigeant.",
    quandPayerTitle:"Quand faut-il payer des charges sociales en SARL et en SAS ?",
    quandPayer : "Le montant des cotisations sociales à payer diffère selon : le régime juridique choisi et la rémunération du dirigeant.  En pratique : en SARL, il y a des cotisations minimales à payer, même si le gérant majoritaire n’est pas rémunéré. À l’inverse, dans le cadre d’une SAS, il n’y a pas de charges si le dirigeant n’est pas rémunéré. Les charges sociales sont à déclarer et à verser avant le 5 ou le 15 du mois. La déclaration se fait auprès de l'Urssaf, en utilisant la déclaration sociale nominative (DSN). Bon à savoir : le dirigeant d’une SAS et le gérant d’une SARL ne sont pas liés à leur entreprise par un contrat de travail, mais par un mandat social. Ce dernier leur permet de percevoir une rémunération pour les fonctions assurées au sein de leur société. Ce mandat peut être rémunéré ou non, selon les indications des statuts. En cas de rémunération, le montant de celle-ci est décidé lors d’une assemblée générale ordinaire en présence des associés. Il inclut la rémunération et les dividendes. Par ailleurs, il est possible de cumuler un contrat de travail et un mandat social, notamment dans le cadre d’un gérant minoritaire de SARL. Cependant, ces situations restent difficiles à mettre en place dans de petites structures, car les fonctions du gérant et du salarié doivent être bien distinctes.",
    quelTauxTitle:"Quel est le taux de cotisations sociales en SARL ou en SAS sur la rémunération du dirigeant ?",
    quelTaux:"Il existe des différences au niveau du taux des charges sociales payées par une SARL et une SAS. Dans le cadre d’une SARL : L’importance des charges varie en fonction de la participation au capital social du dirigeant. Pour le gérant majoritaire : Des charges sociales sont à régler lors de la création de l’entreprise sous la forme d’un versement forfaitaire. Celui-ci est fixé selon le PASS (plafond annuel de la Sécurité sociale) et son montant diffère selon les années. Par la suite, le montant des charges varie selon la rémunération du dirigeant de la SARL. Bon à savoir : même si le dirigeant n’est pas rémunéré, il doit cependant verser des cotisations minimales. La moyenne de ces charges s’élève à environ 45 à 50 % de la rémunération. Ce taux peut cependant varier. D’ailleurs, plus la rémunération du dirigeant est élevée, plus ce taux sera faible. Dans le cadre d’une SAS : En cas de rémunération, le dirigeant est redevable de cotisations, à hauteur de 40 % de charges patronales et 22 % de charges salariales en 2023 sur le salaire brut. Il n’y a pas de cotisation à payer si le dirigeant n’est pas rémunéré. Dans ce cas, le dirigeant de la SAS ne bénéficie d’aucune couverture sociale. Il peut toutefois souscrire à un contrat de prévoyance à titre personnel par exemple."
}]
